CREATE TABLE `db_user` (
  `ID_USER` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `FIRST_NAME` varchar(100) NOT NULL,
  `LAST_NAME` varchar(100) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `PASSWORD` varchar(100) NOT NULL,
  `PROVINSI` varchar(100) DEFAULT NULL,
  `CITY` varchar(100) DEFAULT NULL,
  `DISTRICTS` varchar(100) DEFAULT NULL,
  `PHOTO` longblob DEFAULT NULL,
  `PHONE` int(22) DEFAULT NULL,
  `FAVORITE` decimal(50,0) DEFAULT NULL
);

CREATE TABLE `cart` (
  `ID_CART` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `ID_USER` int(11) DEFAULT NULL,
  `PROMO` varchar(100) DEFAULT NULL,
  `PRICE` decimal(50,0) DEFAULT NULL,
  `DELIVERY_CHARGE` decimal(50,0) DEFAULT NULL,
  `GRAND_TOTAL` decimal(50,0) DEFAULT NULL,
  `status` varchar(100) NOT NULL,
   FOREIGN KEY (ID_USER) REFERENCES db_user(ID_USER)
);

CREATE TABLE `brand` (
  `ID_BRAND` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `NAME` varchar(100) DEFAULT NULL
);

CREATE TABLE `product` (
  `ID_PRODUCT` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL, 
  `ID_BRAND` int(11) DEFAULT NULL,
  `PRICE` decimal(50,0) NOT NULL,
  `DISCOUNT` decimal(50,0) DEFAULT NULL,
  `QUANTITY` decimal(50,0) NOT NULL,
  `gambar` varchar(100) NOT NULL,
  `tmp_discount` int(11) NOT NULL,
  `product_detail` mediumtext NOT NULL,
  FOREIGN KEY (ID_BRAND) REFERENCES brand(ID_BRAND)
);

CREATE TABLE `cart_item` (
  `ID_CART_ITEM` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `ID_CART` int(11) DEFAULT NULL,
  `ID_PRODUCT` int(11) DEFAULT NULL,
  `PRICE` decimal(50,0) DEFAULT NULL,
  `DISCOUNT` decimal(50,0) DEFAULT NULL,
  `QUANTITY` decimal(50,0) DEFAULT NULL,
  `tmp_price` int(11) NOT NULL,
  FOREIGN KEY (ID_CART) REFERENCES cart(ID_CART),
  FOREIGN KEY (ID_PRODUCT) REFERENCES product(ID_PRODUCT)
);

CREATE TABLE `category` (
  `ID_CATEGORY` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL
);

CREATE TABLE `category_product` (
  `id_kunci` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `ID_CATEGORY` int(11) DEFAULT NULL,
  `ID_PRODUCT` int(11) DEFAULT NULL,
  FOREIGN KEY (ID_CATEGORY) REFERENCES category(ID_CATEGORY),
  FOREIGN KEY (ID_PRODUCT) REFERENCES product(ID_PRODUCT)
);

CREATE TABLE `checkout` (
  `ID_CHECKOUT` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `NAME` varchar(100) DEFAULT NULL,
  `ADDRESS` varchar(1000) DEFAULT NULL,
  `COUNTRY` varchar(100) DEFAULT NULL,
  `PAYMENT` varchar(20) DEFAULT NULL,
  `NAME_CARD` varchar(100) DEFAULT NULL,
  `NUMBER_CARD` int(100) DEFAULT NULL,
  `EXPIRE` date DEFAULT NULL,
  `CVV` int(3) DEFAULT NULL,
  `ID_CART` int(11) DEFAULT NULL,
  FOREIGN KEY (ID_CART) REFERENCES cart(ID_CART)
);
